server:
  port: @consumer.port@
spring:
  # 应用信息
  application:
    name: @module.stream.rmq.consumer@
  # RabbitMq 配置
  rabbitmq:
    host: @rmq.host@
    port: @rmq.port@
    username: @rmq.username@
    password: @rmq.password@
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
      bindings:
        input:
          # 指定了消息发送的目的地，对应 RabbitMQ，会发送到 exchange
          destination: cloud-stream-rmq
          # 用于指定消息的类型
          content-type: application/json

# eureka 客户端配置
eureka:
  client:
    register-with-eureka: @register.with.eureka@
    fetch-registry: @fetch.registry@
    service-url:
      defaultZone: @eureka.zone@

info:
  app:
    name: @module.stream.rmq.consumer@
  company:
    name: @project.groupId@
  bulid:
    artifactId: @project.artifactId@
    version: @project.version@

# 应用管理
management:
  endpoint:
    # 是否启用 shutdown 关闭应用
    shutdown:
      enabled: true
  endpoints:
    web:
      # 开启所有端点
      exposure:
        include: "*"

