server:
  port: @cloud.config.server.port@
spring:
  application:
    name: @cloud.config.server@
  cloud:
    # 配置中心
    config:
      server:
        git:
          # 远程仓库地址
          uri: https://github.com/HanJJIE/cloud
          # 默认分支
          default-label: master
          # 配置文件路径
          search-paths:
            - /cloud-config-server/cfg
  # RabbitMq 配置
  rabbitmq:
    host: @rmq.host@
    port: @rmq.port@
    username: @rmq.username@
    password: @rmq.password@

# Eureka 客户端配置
eureka:
  client:
    register-with-eureka: @register.with.eureka@
    fetch-registry: @fetch.registry@
    service-url:
      defaultZone: @eureka.zone@

# 暴露 bus 刷新配置端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"