server:
  port: @cloud.config.port@
spring:
  application:
    name: @module.cloud.config@
  cloud:
    # 配置中心
    config:
      server:
        git:
          uri: https://github.com/HanJJIE/cloud
          default-label: master
          search-paths:
            - /cloud-config-server/cfg
# eureka 客户端配置
eureka:
  client:
    register-with-eureka: @register.with.eureka@
    fetch-registry: @fetch.registry@
    service-url:
      defaultZone: @eureka.zone@