# 端口 80
server:
  port: @consumer.port@
spring:
  # 应用信息
  application:
    name: @module.consumer.openfeign@

# eureka 客户端配置
eureka:
  client:
    register-with-eureka: @register.with.eureka@
    fetch-registry: @fetch.registry@
    service-url:
      defaultZone: @eureka.zone@

info:
  app:
    name: @module.consumer.openfeign@
  company:
    name: @project.groupId@
  bulid:
    artifactId: @project.artifactId@
    version: @project.version@

provider:
  goods: @module.provider.goods@

# 配置请求超时
openfeign:
  # 读取资源所用的时间
  read-timeout: 3000
  # 建立连接所使用的时间
  connection-timeout: 3000