spring:
  profiles:
    active: dev
info:
  app:
    name: @module.alibaba.nacos.provider@
  company:
    name: @project.groupId@
  bulid:
    artifactId: @project.artifactId@
    version: @project.version@

# 应用管理
management:
  endpoint:
    # 是否启用 shutdown 关闭应用
    shutdown:
      enabled: true
  endpoints:
    web:
      # 开启所有端点
      exposure:
        include: "*"
