# 端口 8081
server:
  port: 8081
spring:
  # 应用信息
  application:
    name: cloud-provider-payment
  # 数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://@database.host@:@database.port@/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: @database.username@
    password: @database.password@
    druid:
      initial-size: 5
      max-active: 10
      max-wait: 3000
      min-idle: 3
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
      validation-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# 持久化框架
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.hanjjie.cloud.entities;top.hanjjie.cloud.dto

# eureka 客户端配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: @eureka.zone@