server:
  port: @eureka.port@
eureka:
  instance:
    # eureka 服务端的实例名称
    hostname: @eureka.hostname@
  client:
    # 是否向注册中心注册自己
    register-with-eureka: false
    # 是否提取注册表
    fetch-registry: false
    service-url:
      # 客户端访问地址
      defaultZone: @registry.with.zone@