server:
  port: @consumer.port@

spring:
  # 应用信息
  application:
    name: @module.zk.consumer@
  # 注册中心 zookeeper 配置
  cloud:
    zookeeper:
      connect-string: @vm1.host@:@zk.port@

info:
  app:
    name: @module.zk.consumer@
  company:
    name: @project.groupId@
  bulid:
    artifactId: @project.artifactId@
    version: @project.version@

provider:
  zk: http://@module.zk.provider@